root: true
extends:
  - plugin:react/recommended
  - prettier
parser: babel-eslint
settings:
  react:
    version: "0.16"
env:
  browser: true
  es6: true
  mocha: true
  node: true
globals:
  "$": true
  inkdrop: true
rules:
  no-useless-escape: 0
  prefer-const: 2
  no-unused-vars:
    - 2
    -
      argsIgnorePattern: ^_
      varsIgnorePattern: ^_
  react/display-name: 0
